motion_vae_gan:
  # Optional: mld_vae, vposert_vae
  target: mola.models.architectures.mola_vae_gan.MoLAVAEGAN
  params:
    arch: 'encoder_decoder'
    ff_size: 1024
    num_layers: 9
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: 'gelu'
    position_embedding: 'learned'
    latent_dim: ${model.latent_dim}
    nfeats: ${DATASET.NFEATS}
    ablation: ${TRAIN.ABLATION}
